#!/usr/bin/env bash
#?
# build-check - Ensures required files and environment variables are present
#
# USAGE
#	build-check
#
# BEHAVIOR
#
# 	Checks for the ssh_private_key file and the SSH_NAME, SSH_EMAIL, and
#	SSH_PASSWORD environment variables.
#?
if [ ! -f ssh_private_key ]; then 
	echo "Error: ssh_private_key file must be in directory" >&2
	exit 1
fi

if [ -z "$SSH_NAME" ]; then
	echo "Error: SSH_NAME environment variable must be set" >&2
	exit 1
fi

if [ -z "$SSH_EMAIL" ]; then
	echo "Error: SSH_EMAIL environment variable must be set" >&2
	exit 1
fi

if [ -z "$SSH_PASSWORD" ]; then
	echo "Error: SSH_PASSWORD environment variable must be set" >&2
	exit 1
fi
